In [1]:
# Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
from config import api_key
import eia
import re
from sklearn.linear_model import LinearRegression


In [2]:
#test is api_key variable works
#remove this line output when making public
api_key

'021bf1d89256205c8528b6d4475485b3'

In [3]:
#save variable to call in api data w/ key
api = eia.API(api_key)

In [5]:
#test one api ending; import to pandas dataframe
newdf=api.data_by_series(series='TOTAL.TETCBUS.M')
dataframe1=pd.DataFrame(newdf)
dataframe1.head()

Total Primary Energy Consumption, Monthly (Trillion Btu)
1973 01                                            7226.265       
1973 02                                            6594.709       
1973 03                                            6524.198       
1973 04                                            5944.336       
1973 05                                            6074.551

In [6]:
#add index (unique identifier)
dataframe1=dataframe1.reset_index()
dataframe1=dataframe1.rename(columns={"index":"Time"})
dataframe1.head()

Time  Total Primary Energy Consumption, Monthly (Trillion Btu)
0  1973 01                                            7226.265       
1  1973 02                                            6594.709       
2  1973 03                                            6524.198       
3  1973 04                                            5944.336       
4  1973 05                                            6074.551

In [7]:
#call on first item using index 
dataframe1["Time"][0]

'1973 01 '

In [8]:
#split time calumn into separate year and month (test on first line)
year = re.findall('....', (dataframe1['Time'][0]))[0]
month = re.findall('....', (dataframe1['Time'][0]))[1]

print(f"year = {year}")
print(f"month = {month}")

year = 1973
month =  01 


In [9]:
#create empty lists for future month and year columns
year = []
month = []
counter = 0

In [10]:
#iterate to split all time columns into year/month; add to respective list
for time in dataframe1['Time']:
    year.append(re.findall('....', (dataframe1['Time'][counter]))[0])
    month.append(re.findall('....', (dataframe1['Time'][counter]))[1])
    counter = counter + 1


In [11]:
#add month and year columns to df
dataframe1['Year'] = year
dataframe1['Month'] = month

In [12]:
dataframe1.head()

Time  Total Primary Energy Consumption, Monthly (Trillion Btu)  Year  \
0  1973 01                                            7226.265         1973   
1  1973 02                                            6594.709         1973   
2  1973 03                                            6524.198         1973   
3  1973 04                                            5944.336         1973   
4  1973 05                                            6074.551         1973   

  Month  
0   01   
1   02   
2   03   
3   04   
4   05

In [56]:
energy_consumption_df = dataframe1[["Year", "Month", "Total Primary Energy Consumption, Monthly (Trillion Btu)"]]

# "Total Primary Energy Consumption, Monthly (Trillion Btu)", "Total Primary Energy Consumed by the Commercial Sector, Monthly (Trillion Btu)", "Total Primary Energy Consumed by the Industrial Sector, Monthly (Trillion Btu)", "Total Primary Energy Consumed by the Residential Sector, Monthly (Trillion Btu)", "Total Primary Energy Consumed by the Transportation Sector, Monthly (Trillion Btu)"

energy_consumption_df.head()

Year Month  Total Primary Energy Consumption, Monthly (Trillion Btu)
0  1973   01                                            7226.265       
1  1973   02                                            6594.709       
2  1973   03                                            6524.198       
3  1973   04                                            5944.336       
4  1973   05                                            6074.551

In [57]:
energy_consumption_test = energy_consumption_df.tail(21)

In [58]:
energy_consumption_train = energy_consumption_df.head(528)

In [59]:
energy_consumption_df.columns[0]

'Year'

In [60]:
# reshape x data into an array
X_train = energy_consumption_train.as_matrix(columns=energy_consumption_df.columns[:2])

X_test = energy_consumption_test.as_matrix(columns=energy_consumption_df.columns[:2])

/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  from ipykernel import kernelapp as app
/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [61]:
energy_consumption_df.columns[:2]

Index(['Year', 'Month'], dtype='object')

In [62]:
# reshape y data into an array
y_train = energy_consumption_train.as_matrix(columns=energy_consumption_df.columns[2:3])

y_test = energy_consumption_test.as_matrix(columns=energy_consumption_df.columns[2:3])


/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  from ipykernel import kernelapp as app
/Users/julia/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel/__main__.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [63]:
print(X_train)

[['1973' ' 01 ']
 ['1973' ' 02 ']
 ['1973' ' 03 ']
 ...
 ['2016' ' 10 ']
 ['2016' ' 11 ']
 ['2016' ' 12 ']]


In [64]:
from numpy import shape

In [65]:
shape(X_train)

(528, 2)

In [66]:
shape(y_train)

(528, 1)

In [67]:
print(y_train)

[[7226.265]
 [6594.709]
 [6524.198]
 [5944.336]
 [6074.551]
 [5805.318]
 [5954.498]
 [6194.365]
 [5776.048]
 [6177.455]
 [6521.876]
 [6889.701]
 [6906.707]
 [6316.938]
 [6373.851]
 [5863.745]
 [5867.145]
 [5644.753]
 [5988.038]
 [6018.263]
 [5713.814]
 [6184.96 ]
 [6238.457]
 [6845.56 ]
 [7059.014]
 [6171.542]
 [6386.257]
 [5800.645]
 [5494.457]
 [5438.115]
 [5671.861]
 [5747.213]
 [5501.291]
 [5911.74 ]
 [5853.242]
 [6929.591]
 [7315.131]
 [6396.086]
 [6394.82 ]
 [5858.227]
 [5796.389]
 [5827.441]
 [6027.641]
 [5973.736]
 [5742.648]
 [6247.77 ]
 [6732.906]
 [7661.524]
 [7855.623]
 [6657.899]
 [6577.61 ]
 [5983.088]
 [6000.884]
 [6089.198]
 [6199.376]
 [6304.07 ]
 [6083.524]
 [6276.021]
 [6488.691]
 [7445.772]
 [7724.961]
 [7055.634]
 [6969.369]
 [6173.557]
 [6341.706]
 [6152.956]
 [6343.727]
 [6499.555]
 [6091.208]
 [6428.593]
 [6689.161]
 [7479.492]
 [8096.05 ]
 [7413.492]
 [7155.015]
 [6291.051]
 [6351.355]
 [6146.792]
 [6280.572]
 [6496.817]
 [6056.294]
 [6546.994]
 [6682.793]
 [73

In [68]:
model = LinearRegression()

In [69]:
model.fit(X_train, y_train)

score = model.score(X, y)
print(f"R2 Score: {score}")

R2 Score: 0.6272777407946701


In [70]:
coef = model.coef_
coefyear = coef[0][0]
coefmonth = coef[0][1]
print(f"Year coefficient: {coefyear}")
print(f"Month coefficient: {coefmonth}")

Year coefficient: 58.333951092318536
Month coefficient: -29.792104259376973


In [71]:
y_int = model.intercept_[0] 
print(f"y-intercept: {y_int}")

y-intercept: -108806.97588579185


In [72]:
print(f"Y = mx + b formula")
print("---------------------")
print(f"Usage = {coefyear}*year {coefmonth}*month {y_int}")

Y = mx + b formula
---------------------
Usage = 58.333951092318536*year -29.792104259376973*month -108806.97588579185


In [73]:
print("actual value")
print(y[200])
print("predicted value")
print(model.predict([X[200]])[0])

actual value
[6484.541]
predicted value
[6951.1238985]


In [74]:
X[200]

array(['1989', ' 09 '], dtype=object)

In [75]:
prediction = ['2020', '09']
prediction_array = np.asarray(prediction)
prediction_array

array(['2020', '09'], dtype='<U4')

In [32]:
#model.predict([X[200]])[0]
X[200]

array(['1989', ' 09 '], dtype=object)

In [76]:
prediction_array = prediction_array.astype(float)
prediction_array

array([2020.,    9.])

In [77]:
model.predict([prediction_array])

array([[8759.47638236]])

In [78]:
model.predict(X_test)

array([[8822.81136316],
       [8793.0192589 ],
       [8763.22715464],
       [8733.43505038],
       [8703.64294612],
       [8673.85084186],
       [8644.0587376 ],
       [8614.26663334],
       [8584.47452908],
       [8554.68242482],
       [8524.89032056],
       [8495.0982163 ],
       [8881.14531425],
       [8851.35320999],
       [8821.56110573],
       [8791.76900147],
       [8761.97689721],
       [8732.18479295],
       [8702.39268869],
       [8672.60058443],
       [8642.80848017]])

In [83]:
print(y_test)

[[8980.434]
 [7622.006]
 [8433.752]
 [7457.019]
 [7809.195]
 [7973.908]
 [8441.678]
 [8307.883]
 [7636.766]
 [7845.024]
 [8135.75 ]
 [9236.555]
 [9655.467]
 [8075.048]
 [8684.524]
 [7885.539]
 [8021.157]
 [8149.256]
 [8606.516]
 [8707.549]
 [7870.618]]


In [81]:
#forecast error = (actual - predicted) / actual

actual = sum(y_test)
predicted = sum(model.predict(X_test))

error = (predicted - actual) / actual

percent_error = error*100

print(f"percent error: {percent_error} %")

percent error: [5.31856473] %


In [86]:
x_axis = dataframe1["Time"].tail(21)
y1 = y_test
y2 = model.predict(X_test)

In [88]:
import plotly
import plotly.plotly as ply
import cufflinks as cf
from plotly.plotly import plot_mpl
import plotly.graph_objs as go
plotly.tools.set_credentials_file(username='disco_nap', api_key='84gBOgUqBKJnD1eR2tFV')


In [ ]:
#make a plot of time v. predictions and time v. actuals